<a href="https://colab.research.google.com/github/Seb85vickz/Seba-01/blob/main/Python_Code_review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Install Libraries

In [2]:
import torch
from torch import nn # import torch.nn as nn

In [3]:
x = 5
y = 6
x, y = 5, 6
print(x)

5


In [4]:
type(x)

int

In [5]:
def add_mult_2(a, b):
  return 2*(a + b)

In [6]:
add_mult_2(1,2)

6

In [7]:
class Net(nn.Module):
  def __init__(self, imput_sz=1):
    super(Net, self).__init__()
    self.layer = nn.Linear(imput_sz, 1)
    self.input_sz = imput_sz

  def forward(self, x):
    x = self.layer(x)
    return x

In [8]:
model1 = Net (imput_sz=10)

In [9]:
model2 = Net()

In [10]:
model2.input_sz

1

In [11]:
input = torch.tensor(2.).unsqueeze(0)
input

tensor([2.])

In [12]:
model2.forward(input)

tensor([0.1296], grad_fn=<ViewBackward0>)

In [13]:
model2(input)

tensor([0.1296], grad_fn=<ViewBackward0>)